


CREATE TABLE USUARIO(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);

CREATE TABLE ESTADO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	SIGLA VARCHAR NOT NULL
);

CREATE TABLE CIDADE(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	ESTADO_ID VARCHAR NOT NULL REFERENCES ESTADO(ID)
);


CREATE TABLE FUNCIONARIO(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	LOGRADOURO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
	USUARIO_ID NOT NULL REFERENCES USUARIO(ID),
	ESTADO VARCHAR REFERENCES BAIRRO(ID),
	CIDADE VARCHAR REFERENCES CIDADE(ID),
	BAIRRO VARCHAR REFERENCES BAIRRO(ID)
);



CREATE TABLE CLIENTE(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	TELEFONE2 VARCHAR,
	LOGRADOURO VARCHAR NOT NULL,
	BAIRRO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
	USUARIO_ID NOT NULL REFERENCES USUARIO(ID),
	STATUS INT NOT NULL,
	EMAIL VARCHAR,
	ESTADO VARCHAR REFERENCES BAIRRO(ID),
	CIDADE VARCHAR REFERENCES CIDADE(ID),
	BAIRRO VARCHAR REFERENCES BAIRRO(ID)
);

CREATE TABLE ESCRITOR(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);


CREATE TABLE MULTA(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	VALOR DOUBLE NOT NULL
);


CREATE TABLE ASSUNTO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);

CREATE TABLE EDITORA(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME_FANTASIA VARCHAR NOT NULL,
	CNPJ VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL
);


CREATE TABLE OBRA(

	ID SERIAL NOT NULL PRIMARY KEY,
	ISBN VARCHAR NOT NULL,
	ANO_PUBLICACAO DATE NOT NULL,
	TITULO VARCHAR NOT NULL,
	QUANTIDADE INT NOT NULL VARCHAR,
	EDITORA_ID INT REFERENCES EDITORA(ID)
	MULTA_ID INT NOT NULL REFERENCES MULTA(ID),
	EDICAO VARCHAR

);


CREATE TABLE OBRA_AUTOR(
	ID SERIAL NOT NULL PRIMARY KEY,
	AUTOR_ID INT NOT NULL REFERENCES AUTOR(ID)
	OBRA_ID INT NOT NULL REFERENCES OBRA(ID)
);


CREATE TABLE ASSUNTO_OBRA(
	ID SERIAL NOT NULL PRIMARY KEY,
	ASSUNTO_ID INT NOT NULL REFERENCES ASSUNTO(ID)
	OBRA_ID INT NOT NULL REFERENCES OBRA(ID)
);

CREATE TABLE EXEMPLAR(

	ID SERIAL NOT NULL PRIMARY KEY,
	DATA_AQUISICAO TIMESTAMP NOT NULL,
	STATUS INT NOT NULL,
	ENDERECO VARCHAR NOT NULL
);



CREATE TABLE EMPRESTIMO(

	ID SERIAL NOT NULL PRIMARY KEY,
	EXEMPLAR_ID INT NOT NULL REFERENCES EXEMPLAR(ID),
	DATA_EMPRESTIMO TIMESTAMP NOT NULL,
	FUNCIONARIO_ID INT NOT NULL REFERENCES FUNCIONARIO(ID),
	DATA_DEVOLUCAO TIMESTAMP NOT NULL,
	CLIENTE_ID INT NOT NULL REFERENCES CLIENTE(ID)
);
