


CREATE TABLE USUARIO(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);



CREATE TABLE FUNCIONARIO(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	LOGRADOURO VARCHAR NOT NULL,
	BAIRRO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
	USUARIO_ID NOT NULL REFERENCES USUARIO(ID)
);



CREATE TABLE CLIENTE(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	LOGRADOURO VARCHAR NOT NULL,
	BAIRRO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
	USUARIO_ID NOT NULL REFERENCES USUARIO(ID),
	STATUS INT NOT NULL,
	EMAIL VARCHAR
);

CREATE TABLE ESCRITOR(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	
);

CREATE TABLE LIVRO(



);