CREATE TABLE USUARIO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);


CREATE TABLE ESTADO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	SIGLA VARCHAR NOT NULL
);


CREATE TABLE CIDADE(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	ESTADO_ID INT NOT NULL REFERENCES ESTADO(ID)
);


CREATE TABLE BAIRRO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	CIDADE_ID INT NOT NULL REFERENCES CIDADE(ID)
);


CREATE TABLE FUNCIONARIO(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	USUARIO_ID INT NOT NULL REFERENCES USUARIO(ID),
	ESTADO_ID INT REFERENCES ESTADO(ID),
	CIDADE_ID INT REFERENCES CIDADE(ID),
	BAIRRO_ID INT REFERENCES BAIRRO(ID),
	LOGRADOURO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL
);


CREATE TABLE CLIENTE(

	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	TELEFONE VARCHAR NOT NULL,
	TELEFONE2 VARCHAR,
	DATA_NASCIMENTO DATE NOT NULL,
	USUARIO_ID INT NOT NULL REFERENCES USUARIO(ID),
	STATUS INT NOT NULL,
	EMAIL VARCHAR,
	ESTADO_ID INT REFERENCES ESTADO(ID),
	CIDADE_ID INT REFERENCES CIDADE(ID),
	BAIRRO_ID INT REFERENCES BAIRRO(ID),
	LOGRADOURO VARCHAR NOT NULL,
	NUMERO VARCHAR NOT NULL
);


CREATE TABLE MULTA(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	VALOR FLOAT NOT NULL
);


CREATE TABLE ASSUNTO(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);


CREATE TABLE EDITORA(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME_FANTASIA VARCHAR NOT NULL,
	CNPJ VARCHAR NOT NULL,
	CIDADE_ID INT REFERENCES CIDADE(ID),
	TELEFONE VARCHAR NOT NULL
);


CREATE TABLE OBRA(

	ID SERIAL NOT NULL PRIMARY KEY,
	ISBN VARCHAR NOT NULL,
	ANO_PUBLICACAO DATE NOT NULL,
	TITULO VARCHAR NOT NULL,
	QUANTIDADE INT NOT NULL,
	EDITORA_ID INT REFERENCES EDITORA(ID),
	MULTA_ID INT NOT NULL REFERENCES MULTA(ID),
	EDICAO VARCHAR

);


CREATE TABLE AUTOR(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL
);


CREATE TABLE OBRA_AUTOR(
	ID SERIAL NOT NULL PRIMARY KEY,
	AUTOR_ID INT NOT NULL REFERENCES AUTOR(ID),
	OBRA_ID INT NOT NULL REFERENCES OBRA(ID)
);


CREATE TABLE ASSUNTO_OBRA(
	ID SERIAL NOT NULL PRIMARY KEY,
	ASSUNTO_ID INT NOT NULL REFERENCES ASSUNTO(ID),
	OBRA_ID INT NOT NULL REFERENCES OBRA(ID)
);


CREATE TABLE EXEMPLAR(

	ID SERIAL NOT NULL PRIMARY KEY,
	DATA_AQUISICAO TIMESTAMP NOT NULL,
	STATUS INT NOT NULL,
	OBRA_ID INT NOT NULL REFERENCES OBRA(ID),
	ENDERECO VARCHAR NOT NULL
);


CREATE TABLE EMPRESTIMO(

	ID SERIAL NOT NULL PRIMARY KEY,
	EXEMPLAR_ID INT NOT NULL REFERENCES EXEMPLAR(ID),
	CLIENTE_ID INT NOT NULL REFERENCES CLIENTE(ID),
	FUNCIONARIO_ID INT NOT NULL REFERENCES FUNCIONARIO(ID),
	DATA_EMPRESTIMO TIMESTAMP NOT NULL,
	DATA_DEVOLUCAO_PREV TIMESTAMP NOT NULL,
	DATA_DEVOLUCAO TIMESTAMP NOT NULL
	
);
